name: CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: authn-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Tests
#        run: |
#          cargo build --verbose
#          cargo test --verbose
      - name: Build image
        run: docker build -t authn-api .

      - name: Tag image latest
        run: |
          docker tag authn-api ppaquin/authn-api:latest
          docker tag authn-api ppaquin/authn-api:${{github.sha}}
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push latest
        run: |
          docker push ppaquin/authn-api:latest
          docker push ppaquin/authn-api:${{github.sha}}
